export const getDomRefs = () => ({
  navLinks: document.querySelectorAll('[data-nav]'),
  views: document.querySelectorAll('[data-view]'),
  pageTitle: document.querySelector('#page-title'),
  formMode: document.querySelector('#form-mode'),
  form: document.querySelector('#news-form'),
  tbody: document.querySelector('#news-table-body'),
  refreshButton: document.querySelector('#refresh-news'),
  clearButton: document.querySelector('#clear-form'),
  notice: document.querySelector('#notice'),
  saveButton: document.querySelector('#save-btn'),
  searchInput: document.querySelector('#search-news'),
  placementFilter: document.querySelector('#filter-placement'),
  previewTitle: document.querySelector('#preview-title'),
  previewSummary: document.querySelector('#preview-summary'),
  previewLabel: document.querySelector('#preview-label'),
  previewImage: document.querySelector('#preview-image'),
  totalNews: document.querySelector('#total-news'),
  allNewsCount: document.querySelector('#all-news-count'),
  spotlightNews: document.querySelector('#spotlight-news'),
  sideNews: document.querySelector('#side-news'),
  featureNews: document.querySelector('#feature-news'),
})
